# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 373fdd832f406aa5970ed280a7e2bb580e42f56647ac1b6660aa516d1e593f05f41e88354b198eed8dd64183dbce0438b4215e3f36db3918aeeb935fb444fd88

test:
  secret_key_base: 025a8217bcf98797b2c513cae9758aab88ee463d437e43455ec76d3d7073a490c0369f345d8f5fa6c9304c7588281dcf8186ebbcd9d9ef22b1c8389206af8c9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
